kind: pipeline
name: default
type: docker

trigger:
  branch:
  - dev-docker-container
  event:
  - push

steps:
  - name: credentials
    image: busybox
    environment:
      BQCREDS:
        from_secret: audev-bigquery-default
      ADCREDS:
        from_secret: admanager-auth
      APICREDS:
        from_secret: config
    commands:
      - echo $BQCREDS > audev-bigquery-default.json
      - echo $ADCREDS > admanager-auth.json
      - echo $APICREDS > config.json

  - name: build-import
    image: plugins/gcr
    settings:
      dockerfile: import/Dockerfile
      registry: eu.gcr.io
      repo: zeitonline-210413/audev-kennzahlenupdate
      tags:
        - latest
        - ${DRONE_COMMIT}
      environment:
        VERSION: "${DRONE_COMMIT}"
      json_key:
        from_secret: gcp_service_account
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build-forecast
    image: plugins/gcr
    settings:
      dockerfile: forecast/Dockerfile
      registry: eu.gcr.io
      repo: zeitonline-210413/audev-kennzahlenupdate
      tags:
        - latest
        - ${DRONE_COMMIT}
      environment:
        VERSION: "${DRONE_COMMIT}"
      json_key:
        from_secret: gcp_service_account
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: secret
name: gcp_service_account
get:
  path: zon/v1/gcp/zeitonline-gke-misc-prod/gke/production/ci/audev-kennzahlenupdate
  name: key
