kind: pipeline
name: default

trigger:
  branch:
  - dev-docker-container
  event:
  - push

steps:
  - name: credentials
    image: busybox
    environment:
      BQCREDS:
        from_secret: audev-bigquery-default
      ADCREDS:
        from_secret: admanager-auth
      APICREDS:
        from_secret: config
    commands:
      - echo $BQCREDS > audev-bigquery-default.json
      - echo $ADCREDS > admanager-auth.json
      - echo $APICREDS > config.json

  - name: build
    image: plugins/gcr
    settings:
      registry: eu.gcr.io
      repo: audev-217815/audev-kennzahlenupdate
      tags:
        - latest
        - ${DRONE_COMMIT}
      environment:
        VERSION: "${DRONE_COMMIT}"
      json_key:
        from_secret: gcp_service_account
    volumes:
      - name: docker
        path: /var/run/docker.sock

