version: '3'

services:
  import:
    environment:
      - WT_USER=${WT_USER}
      - WT_PASSWORD=${WT_PASSWORD}
      - WT_CUSTOMER_ID=${WT_CUSTOMER_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - F3_CLIENT_ID=${F3_CLIENT_ID}
      - F3_CLIENT_SECRET=${F3_CLIENT_SECRET}
    build:
      context: .
      dockerfile: import/Dockerfile
    volumes:
      - ${PWD}/audev-217815-kennzahlenupdate-owner.json:/main-app/audev-217815-kennzahlenupdate-owner.json

  forecast:
    environment:
      - WT_USER=${WT_USER}
      - WT_PASSWORD=${WT_PASSWORD}
      - WT_CUSTOMER_ID=${WT_CUSTOMER_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - F3_CLIENT_ID=${F3_CLIENT_ID}
      - F3_CLIENT_SECRET=${F3_CLIENT_SECRET}
    build:
      context: .
      dockerfile: forecast/Dockerfile
    volumes:
      - ${PWD}/audev-217815-kennzahlenupdate-owner.json:/fc-app/audev-217815-kennzahlenupdate-owner.json
