---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import
spec:
  # jobs will run according to kubernetes masters (UTC)
  # consider the time +2h
  schedule: "15 4 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          serviceAccountName: baseproject
          containers:
          - name: app
            image: eu.gcr.io/zeitonline-210413/audev-kennzahlenupdate-import:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure