---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import
spec:
  # jobs will run according to kubernetes masters (UTC)
  # consider the time +2h
  schedule: "15 4 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          serviceAccountName: baseproject
          containers:
          - name: app
            image: eu.gcr.io/zeitonline-210413/audev-kennzahlenupdate-import:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: WT_USER
                valueFrom:
                  secretKeyRef:
                    name: wt-secrets
                    key: wt_user
              - name: WT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: wt-secrets
                    key: wt_password
              - name: WT_CUSTOMER_ID
                valueFrom:
                  secretKeyRef:
                    name: wt-secrets
                    key: wt_customer_id
              - name: SLACK_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: slack-webhook
                    key: slack_webhook
              - name: F3_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: f3-reshin-secrets
                    key: f3_client_id
              - name: F3_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: f3-reshin-secrets
                    key: f3_client_secret
          restartPolicy: OnFailure