---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: forecast
spec:
  schedule: "30 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: eu.gcr.io/zeitonline-210413/audev-kennzahlenupdate-forecast:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 4000m
                memory: 1024Mi
              limits:
                cpu: 6000m
                memory: 3Gi
          restartPolicy: OnFailure