---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: forecast
spec:
  # jobs will run according to kubernetes masters (UTC)
  # consider the time +2h
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          serviceAccountName: baseproject
          containers:
          - name: app
            image: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/kennzahlenupdate-forecast:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 2000m
                memory: 1024Mi
              limits:
                cpu: 6000m
                memory: 3Gi
          restartPolicy: OnFailure