resources:
- cronjob-import.yml
- cronjob-forecast.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /kennzahlenupdate-forecast
  newTag: 7dc2e43cc66615061ddbfdb48184e404df18089f
- name: /kennzahlenupdate-import
  newTag: 7dc2e43cc66615061ddbfdb48184e404df18089f